### ISSUE TITLE
Hint and submit buttons causing crash

### ISSUE THREAD

**Issue by LeahHunt** [EducationShinyAppTeam/Matching_Distributions#1]
If the hint button is clicked at the beginning of the game (before clicking anything else), the app crashes. This applies after the restart button is clicked as well. The same occurs when first entering the game with the Submit button, but the Submit button only has this problem on the first game play (not after restart has been clicked) and if the game is entered using the tabs on the side of the screen instead of the "Go" button.

**Comment by shravanisamala** [comment]
Now, this only happens to me when I hit the hint question mark button before starting the game. The submit button has a little circle with a slash that comes over it before the first game so maybe that could be something do to before the first game.

**Comment by shravanisamala** [comment]
Button issue is now fixed by coding in disabled = TRUE when creating buttons!
